### PR TITLE
Added last updated icon

### PR DESCRIPTION
**Pull request by teddhuff**

### CODE REVIEW

**Comment by CoDEmanX** [comment]
The pencil has a very thin contour and the icon is actually two-colored (black and white). Can you make it more material? (2px stroke width, 2px margins)

**Comment by teddhuff** [comment]
No problem, thought I had done that already.

**Comment by teddhuff** [comment]
Was having issues with getting it just right so made the pencil solid

**Comment by CoDEmanX** [comment]
I think the pencil should have a virtual 2px contour, which would eliminate some of the outer circle's area. That way both components would be separated more clearly.

Overall, I'm still unsure if this isn't too specific as icon. Just a pencil or only a clock should work in most cases. You would need to provide a proper context if course.

See StackExchange for example: they add a pencil icon to comments when it's first edited. Because it's next to the comment date, it's pretty clear that it's time related. The tooltip shows how often it was edited.

An icon like yours would add unnecessary visual noise - which material design tries to reduce.

If you want to use it in context of file attributes (created on, last modified on, last accessed), then it's a bit different story. I think just a pencil would still work if it's displayed in a group with the other two properties (document-plus, pencil and ???). It's actually a lot harder to depict "last accessed" than even it was edited...

**Comment by teddhuff** [comment]
It is intended to show a user that an item was edited that they can not edit.  At this point i am not sure how to create an icon that will meet your criteria and my needs and will just cancel the request.

**Comment by CoDEmanX** [comment]
So it is supposed to mean two things at once? That something was edited, and that it's no longer editable by the user? (Whether the latter is a consequence of the former isn't relevant in my opinion)

If I got that right, you should add a pad lock to the pencil icon. That would express that it's no longer possible to edit. The reason for this can be put in a tooltip for that icon (or make it a link to a help page that explains why it's locked in detail)

**Comment by CoDEmanX** [comment]
Two examples:
pencil-lock https://www.dropbox.com/s/8ho0laokigkic9z/pencil-lock.svg?dl=0
pencil-off https://www.dropbox.com/s/o2e3n9tethsydjz/pencil-off.svg?dl=0

**Comment by teddhuff** [comment]
edited by someone else... think of if if you the consumer are looking at an offer and it was modified just yesterday by the business..

**Comment by Templarian** [comment]
@CoDEmanX Can you move these two icons to a issue request. Id like to get them added.

**Pull request closed without merging**
