### PR TITLE
Add documentation about PHP integration

### PR DESCRIPTION
**Pull request by chteuchteu**

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Thanks for taking this and running with it, @chteuchteu 😃 Definitely better than I could have managed.

I'd still like to see a standalone version for those that don't use NPM, though.

**Comment by chteuchteu** [comment]
@PeterShaggyNoble The pleasure is mine! :-)

In order to avoid requiring npm/yarn, we'd have to publish MaterialDesign-SVG as composer package.
@Templarian : it's quite simple actually, all you have to do is to but adding a composer.json file in the project root dir,

**Comment by Templarian** [comment]
@chteuchteu Yea, we'll need to do that I suppose. Lets shoot to get this setup this weekend.

**Comment by chteuchteu** [comment]
Nice! :)

**Comment by chteuchteu** [comment]
@Templarian : I opened a PR with a shiny `composer.json`: https://github.com/Templarian/MaterialDesign-SVG/pull/8

**Pull request merged**
