### PR TITLE
Guitar icon

### PR DESCRIPTION
**Pull request by FloEdelmann**
I know I shouldn't create pull requests to this repository but the 'Contribute' page is disabled.

Partial fix for issue #135

### CODE REVIEW

**Comment by Templarian** [comment]
I'll get it added tonight.

**Comment by CoDEmanX** [comment]
Can't find it?!

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/guitar I might have removed it for not being material enough. But I agree it is needed. So I'll leave it for now.

**Comment by CoDEmanX** [comment]
It's actually an electric guitar... we should probably make this icon a material-compliant guitar, and possibly add a material-y version of an electric guitar.

**Pull request closed without merging**
