### PR TITLE
Remove progress-question rogue nodes

### LINKED ISSUE #5894: mdi-progress-question horizontal bar
Hi, 

Using firefox (86.0.1 (64-bit)) i'm facing a strange horizontal bar (from the top of the '?' to the top of 'F1' on the screenshot) with this icon (and only this icon). I'm able to reproduce it on the mdi cheatsheet (https://pictogrammers.github.io/@mdi/font/5.4.55/)

image

This doesn't happen with Chrome, and doesn't happen when zooming above 125%. 

Weird..

### PR DESCRIPTION
**Pull request by lcnittl**
This will fix #5894

### CODE REVIEW

**Comment by lcnittl** [comment]
The icon is slightly unsymmetrical (node wise) -- shall this be fixed in this PR too?

**Comment by Templarian** [comment]
This has been fixed. I also shifted the circle to be the correct shape.

Interesting though I thought I had to code that doesn't allow for points to be outside of the 24x24 size when converted to absolute (the format we save).

**Comment by lcnittl** [comment]
Thanks for the fix! Sorry for the follow-up: it appears that the question mark is now off-center by 0.050 px.

I duly struggle to find the original containing repo - otherwise I would have (now) proposed the changes there.

Thanks again, lcnittl

**Comment by mririgoyen** [comment]
We don't manage the library in PRs. It is handled via a system we've built. Once we make the changes there, they propagate our to the repo.

**Comment by Templarian** [comment]
@lcnittl Fixed, oops, that was a bad copy/paste earlier.

**Pull request closed without merging**
