### PR TITLE
Add file-school and file-school-outline

### PR DESCRIPTION
**Pull request by viktor-yakubiv**
The icons are based on the original file and file-outline icons.

The school icon is redrawn from the resized school icon from the repository and positioned according to the material guidelines for icons.

The files were edited in Figma and exported from there without further processing. I am not sure I combined paths properly and would be happy to hear feedback. I needed I can process it with SVGO but I doubt I can do anything manually.

### CODE REVIEW

**Comment by goyney** [comment]
We do not accept PRs into this repository. We have a dedicated icon management system that syncs back here.

Please [open an issue](https://github.com/Templarian/MaterialDesign/issues/new?labels=Icon+Request%2C+Contribution&template=2_contribution.md&title=), [generate previews of your contributions](http://dev.materialdesignicons.com/contribute/github), and include them in a ZIP file on the issue for consideration.

**Comment by viktor-yakubiv** [comment]
Good to know. Thank you @goyney!

**Comment by viktor-yakubiv** [comment]
@goyney I am trying to use the tool but I cannot see a preview for any image even when I copy path data from any existing icon in the repository. I used the latest Chrome Canary to test and this is what I got:

> Uncaught TypeError: Cannot set property 'path' of undefined

tool log

**Comment by goyney** [comment]
@Templarian This is for sure broken right now.

**Comment by Templarian** [comment]
Pushed a fix. Yeah, I really need to run the unit tests it would have caught this. Accidentally passed an array by reference.

@viktor-yakubiv Thanks for the heads up!

**Pull request closed without merging**
