### PR TITLE
Add mdi-preact

### PR DESCRIPTION
**Pull request by levrik**

### CODE REVIEW

**Comment by PeterShaggyNoble** [comment]
Thanks, @levrik. Could you add a link for `mdi-preact`?

**Comment by levrik** [comment]
@PeterShaggyNoble It's the same as for `mdi-react`. The `mdi-preact` package is built from the same repo. I could add the link to the npm page but then we would loose the badges in the title which show the included version of `mdi-svg`.

**Comment by Templarian** [comment]
@levrik Do we need to do anything with this issue?

**Comment by levrik** [comment]
@Templarian This is ready to merge. I've added an extra README for `mdi-preact` to the repo and linked it here.

**Pull request merged**
