### PR TITLE
Added mdi-react as alternative to mdi-material-ui

### PR DESCRIPTION
**Pull request by levrik**
Side note: I will switch to your new SVG-only repo (https://github.com/Templarian/MaterialDesign-SVG) as soon as I have time :)

### CODE REVIEW

**Comment by Templarian** [comment]
Let me know when you have time to update to the `mdi-svg` dependency and I'll merge this. Thanks!

**Comment by levrik** [comment]
@Templarian Okay. I've updated to `mdi-svg` now. One question: There is a `meta.json` in the root of `mdi-svg`. Should that be used instead of iterating over the folder entries in the `svg` folder?

**Comment by Templarian** [comment]
You found a bug @levrik, nah either is fine. The meta.json just gives more data.

I'll release an update to fix the meta.json shortly. Opening a bug in that repo.

**Comment by levrik** [comment]
@Templarian Thanks for merging :)

**Pull request merged**
